---
title: HW2
author: Yian Lin, Haibo Wu, Wakeel Adekunle Kasali
date: 2024-03-01
bibliography: ../references/hw2.bib
---

# Introduction
Consumer behavior regarding daily beverage choices is widely observed, with zero-calorie drinks usually considered as a healthier option. It is reasonable to surmise that methods of sale might impact the sales dynamics of zero-calorie beverages. This study aims to investigate which alternative methods are most effective in encouraging the purchase of zero-calorie drinks. Specifically, there are two primary intervention strategies of interest: one that highlighting the average calorie content in each beverage and/or the amount of exercise needed to burn those calories, and another providing discount information along with explanations for the discounts. To determine the key factors of effect, the consumption patterns of various beverages are compared under the different interventions. The main statistical questions we aim to address include: (1) How do different interventions affect the sales of zero-calorie and sugary beverages, and which strategies are more impactful;
 (2) Whether the effectiveness of the interventions change with site; (3) Compared to the mere amount of calorie, if the calorie-relevant information is more effective.
 
With the given information, we will be approaching the questions and provide statistical advice in the following ways:
  
 *  We will discuss characteristics of the dataset through visualization with appropriate figures and tables, for enhanced insight.
 *  We will illustrate how to construct models to determine the effects of different interventions and capture variations by site.
 
 The structure of the remainder of this report is as follows. Following a brief description about the dataset in Section 2, EDA analysis are employed in Section 3 to visualize the data and prepare for further analysis. Section 4 illustrates how to develop the generalized least squares (GLS) model with the dataset and address the concerned questions. The conclusion and specific suggestions are given in Section 5.
 


# Data Summary
This is a quasi-experiment study for investigating the effects of five interventions  on consumer inclination towards zero-calorie beverages. The dataset contains the daily sales of different types of beverages (including zero-calorie, sugared and others) under various interventions across three sites, from October 27 to May 23. In this study, the daily sales of each type of beverage are used for measuring the consumers' preference on this type of beverage. The crucial variables are the daily sales of zero-calorie beverages, sugared beverages and total of all the beverages, which are measured as continuous data. On the other hand, based on the objectives of the study, the site and intervention should be treated as categorical variables for further analysis, and the days of week are also recorded as a categorical variable to determine potential impacts of time on the outcomes. Additionally, the dataset includes a time-counting variable that captures the timeline of the entire experiment, indicating that each site has around 220 time points. For the entire dataset, the records of these key variables are relatively complete, with sugared and zero-calorie beverages having only a negligible amount of missing data. However, records for other types of beverages show a certain proportion of missing data, which can be considered as missing completely at random based on the given information. 
 
# EDA Analysis


# Formal Analysis


# Conclusions
It is recommended to use daily sales in percentage terms as response variable for the analysis, to better represent the relative consumption of zero-calorie and sugared beverages. Besides the tables showing the missingness of the dataset, the time series plots can be displayed to visualize the daily changes of zero-calorie drinks consumption, and the side by side boxplots can illustrate the relationship between the daily sales and various interventions at each site. 

We suggest to implement GLS for each site to capture the association between changes in beverage consumption and the adopted interventions, allowing us to account for the dependence structure of residuals of the model.  Specifically, `Intervention` and `DofW` should serve as the predictor variables. The optimal model for each site can be determined by comparing the AIC across several candidate models, with each model specifying one of four different correlation structures. Differences in the effectiveness of various interventions and sites are identifiable by comparing the coefficients of the final models. 

\newpage
# References


